name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        run: |
          go test -mod=vendor -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp $(go list ./... | grep -v '/cmd/')
          if [ -f "$GITHUB_WORKSPACE/profile.cov_tmp" ]; then
            grep -v "mocks" $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock" > $GITHUB_WORKSPACE/profile.cov || true
          fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
